[project]
name = 'deidentify-engine'
dynamic = ['version']
description = 'FastAPI based engine with deidentify core'
requires-python = '==3.9.*'
dependencies = [
    'deidentify>=0.7.3',
    'deduce<2.0.0',
    'eval-type-backport>=0.4.0',
    'fastapi[standard]>=0.128.8',
    'fastexcel>=0.16.0',
    'huggingface-hub<1.0',
    'numpy<2.0',
    'nl-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.3.0/nl_core_news_sm-2.3.0.tar.gz',
    'polars[pandas]>=1.36.1',
    'rich>=15.0.0',
    'setuptools<81',
    'torch<2.6',
    'xlsxwriter>=3.2.9',
]

[dependency-groups]
build = [
    'pyinstaller>=6.18.0',
    'setuptools-scm>=9.2.2',
]

dev = [
    'mypy>=1.19.1',
    'pandas-stubs>=2.2.2.240807',
    'pytest>=8.4.2',
    'pytest-cov>=7.0.0',
    'ruff>=0.15.0',
]

[tool.setuptools.packages.find]
include = ['api*', 'core*', 'main*']

[tool.setuptools.dynamic]
version = { file = 'main/VERSION' }

[tool.uv]
package = false
required-version = '>=0.11.2'

[tool.fastapi]
entrypoint = 'run:app'

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ['ALL']
ignore = [
    'SLF001',  # (MEIPASS use for PyInstaller)
    'S101',    # (False positives when using with pytest)
    'S301',    # (Pickle file loading)
    'COM812',  # (Conflicts with ruff formatter)
]

[tool.ruff.lint.pydocstyle]
convention = 'google'

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.format]
quote-style = 'single'

[tool.coverage.run]
data_file = 'pytest/.coverage'

[tool.coverage.html]
directory = 'pytest/html'

[tool.coverage.xml]
output = 'pytest/coverage.xml'

[[tool.mypy.overrides]]
module = 'deidentify.*'
ignore_missing_imports = true

[tool.pytest.ini_options]
python_files = ['tests.py', 'test_*.py', '*_tests.py']
cache_dir = 'pytest/.pytest_cache'
addopts = [
    '--cov=.',
    '--cov-report=term:skip-covered',
    '--cov-report=html',
    '--cov-report=xml',
    '--cov-fail-under=25',
    '-p',
    'no:warnings'
]
